### PR TITLE
Optional sudo usage

### PR DESCRIPTION
**Pull request by DanielBarnes**
In my use case, I have a self-hosted actions runner with limited permissions and cannot use sudo. 

From my testing, sudo is not required in our self-hosted setup to complete the installation and setup. Still, I have added an opt-out flag to disable calling the npm commands with sudo with a default to maintain the existing functionality.

### CODE REVIEW

**Comment by DavidGOrtega** [comment]
@DanielBarnes thanks for the PR!

Currently sudo is only used if its present. With this PR we are making it optional even if its present. Right?

**Comment by DanielBarnes** [comment]
> @DanielBarnes thanks for the PR!
> 
> Currently sudo is only used if its present. With this PR we are making it optional even if its present. Right?

That's correct, In my usage so far, sudo has is present on the system but the actions runner is not being run as a user in the sudoers groups so it was failing.

**Review by DavidGOrtega — APPROVED** [review]
👍 lgtm

🚀

**Comment by 0x2b3bfa0** [comment]
@DanielBarnes, released with #38; sorry for the delays.

**Pull request merged**
