### PR TITLE
Update vega-lite version

### LINKED ISSUE #75: Old vega version - causes conflict with certain plot ecodings
https://github.com/iterative/setup-cml/blob/7eecee79650503f8624b7012b89d27bef4f7de60/src/utils.js#L51

vega-lite version should be bumped to 5 (in fact 5.2.0 is necessary). DVC has recently updated plots to use this vega version and some types of plots cannot be rendered correctly otherwise.

For more details for why this causes problems see this [comment](https://github.com/iterative/dvc-render/issues/8#issuecomment-1172783165) in a related issue

### PR DESCRIPTION
**Pull request by dacbd**
Closes #75

### CODE REVIEW

**Review by 0x2b3bfa0 — APPROVED** [review]
download

**Comment by 0x2b3bfa0** [comment]
**See also**
* https://github.com/iterative/setup-cml/issues/47

**Comment by dacbd** [comment]
> download

hmm break because somehow a user has node12 or break because they are using dvc plots with v5 schema?

**Comment by 0x2b3bfa0** [comment]
> _Break because somehow a user has Node.js 12_

☝🏼🦢⬛ Unlikely, but possible. Fault-induced telemetry will suffice: if there are no complaints, we're good. 😈

**Comment by dacbd** [comment]
well, I tagged the previous commit as v1.1.4 and the squashed commit as v1.2.0 so there is an immediate fix if someone encounters an issue.

**Pull request merged**
