### PR TITLE
perf: inhance version hint

### PR DESCRIPTION
**Pull request by nibilin33**
add npm-api to get latest version when cli --version failed

### CODE REVIEW

**Comment by nibilin33** [comment]
@dacbd here, is it fit for the expect?

**Comment by dacbd** [comment]
@nibilin33 I see what this library is now. We would rather attempt to read and parse the version from the `package.json` that we just installed, instead of calling the npm API to resolve what latest is.

**Comment by nibilin33** [comment]
@dacbd so just print after install? i assume there is something weird in ci, so i try to get info from cloud

**Comment by dacbd** [comment]
@nibilin33 well, determine the path it was installed to, and read the value from the package.json. I don't think we need to assume any weirdness from the CI. You can read `RUNNER_OS` from the env to determine what the appropriate npm/global path is.

**Pull request closed without merging**
