### PR TITLE
Pass environment to `sudo` and fix tests

### LINKED ISSUE #53: Incompatible version of node in latest GitHub ubuntu 20.04 image
In https://github.com/actions/virtual-environments/pull/4395/files, NodeJS 16 has been added to the ubuntu image. I think this is the reason we are hitting that error in our [CI](https://github.com/jupyterlab/jupyterlab/issues/11606) although we are using the GitHub actions to use NodeJS 14. Is there a workaround? Or do we need to wait for https://github.com/iterative/cml/issues/825?

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
May close #53; fixes bugs in the testing workflow. 🐛🔨

### CODE REVIEW

**Review by casperdcl — DISMISSED** [review]

**Comment by 0x2b3bfa0** [comment]
It turns out that `sudo -E` won't transfer `PATH` on most modern systems for the sake of security. Using https://unix.stackexchange.com/a/83194 instead...

**Comment by 0x2b3bfa0** [comment]
Tested and working as expected.

**Comment by 0x2b3bfa0** [comment]
@casperdcl, it looks like I need you to approve again the pull request. 
[](https://xkcd.com/501)

**Review by casperdcl — DISMISSED** [review]

**Comment by casperdcl** [comment]
~did we find a bug in the tests?~

**EDIT**: no, `cml publish` should accept `stdin` in lieu of a filename: https://github.com/iterative/cml/blob/cf7bfd039bc366d781ee897f774ca394f21e3f39/bin/cml/publish.js#L10

**Comment by 0x2b3bfa0** [comment]
Yes, `cml publish` should and does accept `stdin` _in lieu_ of a path, _mais... vous trompez:_ tests actually had a bug, because they were running `cml publish` without a path **and** without `stdin`

**Comment by 0x2b3bfa0** [comment]
Get prepared to give away your soul for the third time in a row.

**Comment by 0x2b3bfa0** [comment]
@casperdcl, this time tests are green before the review request. 😅

**Review by casperdcl — APPROVED** [review]
no souls were promised nor transferred in the granting of this approval

**Pull request merged**
